#!/usr/bin/env python3
"""
gen_icon.py - Convert a PNG image into a Zig sprite constant.

Usage:
    python3 scripts/gen_icon.py <input.png> <output.zig> [options]

Options:
    --name NAME         Sprite variable name (default: input filename stem)
    --step INT          Color quantize step, lower = more colors (default: 32)
    --contrast FLOAT    Contrast enhancement factor (default: 1.6)
    --saturation FLOAT  Saturation enhancement factor (default: 1.8)
    --sharpness FLOAT   Sharpness enhancement factor (default: 2.5)

Example:
    python3 scripts/gen_icon.py assets/icons/raccoon.png kernel/font/icons.zig --name raccoon
"""

import argparse
from pathlib import Path

from PIL import Image, ImageEnhance


def load_and_filter(
    path: str, contrast: float, saturation: float, sharpness: float
) -> Image.Image:
    img = Image.open(path).convert("RGBA")
    rgb = Image.merge("RGB", img.split()[:3])
    alpha = img.split()[3]

    rgb = ImageEnhance.Contrast(rgb).enhance(contrast)
    rgb = ImageEnhance.Color(rgb).enhance(saturation)
    rgb = ImageEnhance.Sharpness(rgb).enhance(sharpness)
    rgb.putalpha(alpha)

    return rgb


def quantize_image(img: Image.Image, step: int):
    w, h = img.size

    def snap(v):
        return (v + step // 2) // step * step

    palette: dict[tuple, int] = {}
    indices: list[int] = []

    for y in range(h):
        for x in range(w):
            r, g, b, a = img.getpixel((x, y))
            if a < 128:
                indices.append(0xFF)
            else:
                key = (snap(r), snap(g), snap(b))
                if key not in palette:
                    palette[key] = len(palette)
                indices.append(palette[key])

    pal_list = sorted(palette.items(), key=lambda e: e[1])
    return w, h, pal_list, indices


def generate_zig(
    name: str, source_file: str, w: int, h: int, palette, indices: list[int]
) -> str:
    lines = [
        f"// Auto-generated by scripts/gen_icon.py from {Path(source_file).name}",
        "// Do not edit manually — re-run the script to regenerate.",
        "",
        'const Color = @import("../drivers/framebuffer.zig").Color;',
        "",
        "pub const transparent: u8 = 0xFF;",
        "",
        "pub const Sprite = struct {",
        "    width: usize,",
        "    height: usize,",
        "    palette: []const Color,",
        "    pixels: []const u8,",
        "};",
        "",
        f"const {name}_palette: [{len(palette)}]Color = .{{",
    ]

    for (r, g, b), idx in palette:
        lines.append(f"    .{{ .r = {r:3}, .g = {g:3}, .b = {b:3} }}, // [{idx:2d}]")

    lines += [
        "};",
        "",
        f"const {name}_pixels: [{w * h}]u8 = .{{",
    ]

    for row in range(h):
        row_data = indices[row * w : (row + 1) * w]
        parts = ", ".join(f"0x{v:02X}" for v in row_data)
        lines.append(f"    {parts},")

    lines += [
        "};",
        "",
        f"pub const {name}: Sprite = .{{",
        f"    .width   = {w},",
        f"    .height  = {h},",
        f"    .palette = &{name}_palette,",
        f"    .pixels  = &{name}_pixels,",
        "};",
        "",
    ]

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Convert a PNG icon into a Zig sprite constant."
    )
    parser.add_argument("input", help="Input PNG file")
    parser.add_argument("output", help="Output Zig file")
    parser.add_argument(
        "--name", help="Sprite variable name (default: input filename stem)"
    )
    parser.add_argument(
        "--step", type=int, default=32, help="Color quantize step (default: 32)"
    )
    parser.add_argument("--contrast", type=float, default=1.6)
    parser.add_argument("--saturation", type=float, default=1.8)
    parser.add_argument("--sharpness", type=float, default=2.5)
    args = parser.parse_args()

    name = args.name or Path(args.input).stem

    img = load_and_filter(args.input, args.contrast, args.saturation, args.sharpness)
    w, h, palette, indices = quantize_image(img, args.step)
    zig_code = generate_zig(name, args.input, w, h, palette, indices)

    Path(args.output).write_text(zig_code)
    print(f"Generated {args.output}: {w}x{h}, {len(palette)} colors, {w * h} pixels")


if __name__ == "__main__":
    main()
