#!/usr/bin/env python3
"""Tiny, dependency-free ticket tracker backed by code comments.

Model
-----
A ticket is a directory under `.tickets/<id>/` whose `ticket.md` is the single
source of truth for mutable state (status, priority, area, notes, attachments).
The code comment is only an *anchor*:

    raw       TODO (<priority>[, <area>]): <message>
    promoted  TODO#<id> (<priority>[, <area>]): <message>

`file:line` locations are never stored by hand: they are resolved live by
grepping for `TODO#<id>`, and the committed `## Code references` block in each
ticket is regenerated (never hand-edited) by `sync`.

Lifecycle
---------
    write a raw TODO  ->  `promote`  ->  TODO#<id> + .tickets/<id>/
    `set <id> <STATUS> [comment]`     ->  update status + append to ## Log
    `close <id> [comment]`            ->  strip the code marker(s),
                                          status CLOSED, move to .tickets/closed/

This script is intentionally stdlib-only and edits `ticket.md` with targeted,
section-aware text surgery so hand-written prose is preserved across updates.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import date
from typing import Optional

# ---------------------------------------------------------------------------
# Configuration (edit here to extend the tool)
# ---------------------------------------------------------------------------

TICKETS_DIR = ".tickets"
CLOSED_SUBDIR = "closed"

# Comment token per source language; also drives which files we scan.
COMMENT_TOKENS = {".zig": "//", ".s": ";"}

STATUSES = ("OPEN", "IN_PROGRESS", "BLOCKED", "CLOSED")
OPEN_STATUSES = ("OPEN", "IN_PROGRESS", "BLOCKED")
PRIORITIES = ("low", "medium", "high")
PRIORITY_RANK = {p: i for i, p in enumerate(("high", "medium", "low"))}

ATTACH_SIZE_WARN = 256 * 1024  # bytes; bigger needs --binary

REFS_BEGIN = "<!-- refs:auto — regenerated by scripts/ticket.py; do not edit below -->"
REFS_END = "<!-- /refs:auto -->"

# `TODO` not followed by `#` -> raw;   `TODO#<id>` -> promoted.
_FIELDS = r"\(\s*([A-Za-z]+)\s*(?:,\s*([^)]*?))?\s*\)\s*:\s*(.*)"
RAW_RE = re.compile(r"TODO(?!#)\s*" + _FIELDS)
PROMOTED_RE = re.compile(r"TODO#(\d+)\s*" + _FIELDS)
LOOSE_RE = re.compile(r"TODO(?:#\d+)?\s*\(")  # used only to flag malformed lines


# ---------------------------------------------------------------------------
# Small data types
# ---------------------------------------------------------------------------


@dataclass
class Marker:
    """A `TODO`/`TODO#id` occurrence found in a source file."""

    path: str  # repo-relative
    line: int  # 1-based
    col: int  # 0-based offset of the leading `TODO`
    raw: bool
    id: Optional[int]
    priority: str
    area: str
    msg: str


@dataclass
class Ticket:
    """Metadata read from a `.tickets/<id>/ticket.md` frontmatter."""

    id: int
    title: str
    status: str
    priority: str
    area: str
    dir: str
    closed: bool


# ---------------------------------------------------------------------------
# Generic helpers
# ---------------------------------------------------------------------------


def fail(msg: str) -> "NoReturn":  # type: ignore[name-defined]
    print(f"ticket: {msg}", file=sys.stderr)
    sys.exit(1)


def repo_root() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        fail("not inside a git repository")
    return out.stdout.strip()


def read_text(path: str) -> str:
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def write_text(path: str, text: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def today() -> str:
    return date.today().isoformat()


def git_add(root: str, *paths: str) -> None:
    subprocess.run(["git", "-C", root, "add", "--", *paths], check=False)


def tracked_files(root: str) -> list[str]:
    """Tracked + untracked-but-not-ignored files (respects .gitignore)."""
    out = subprocess.run(
        ["git", "-C", root, "ls-files", "--cached", "--others", "--exclude-standard"],
        capture_output=True, text=True, check=True,
    )
    # De-duplicate while preserving order (a path can appear cached and other).
    seen, files = set(), []
    for rel in out.stdout.splitlines():
        if rel and rel not in seen:
            seen.add(rel)
            files.append(rel)
    return files


def lang_token(rel: str) -> Optional[str]:
    return COMMENT_TOKENS.get(os.path.splitext(rel)[1].lower())


# ---------------------------------------------------------------------------
# Scanning source for markers
# ---------------------------------------------------------------------------


def scan_markers(root: str) -> list[Marker]:
    markers: list[Marker] = []
    for rel in tracked_files(root):
        if lang_token(rel) is None:
            continue
        try:
            text = read_text(os.path.join(root, rel))
        except (OSError, UnicodeDecodeError):
            continue
        for lineno, line in enumerate(text.split("\n"), start=1):
            m = PROMOTED_RE.search(line)
            if m:
                markers.append(Marker(
                    rel, lineno, m.start(), False, int(m.group(1)),
                    m.group(2).lower(), (m.group(3) or "").strip(), m.group(4).strip(),
                ))
                continue
            m = RAW_RE.search(line)
            if m:
                markers.append(Marker(
                    rel, lineno, m.start(), True, None,
                    m.group(1).lower(), (m.group(2) or "").strip(), m.group(3).strip(),
                ))
    return markers


def find_malformed(root: str) -> list[tuple[str, int, str]]:
    """Lines that look like a TODO marker but parse as neither raw nor promoted."""
    bad = []
    for rel in tracked_files(root):
        if lang_token(rel) is None:
            continue
        try:
            text = read_text(os.path.join(root, rel))
        except (OSError, UnicodeDecodeError):
            continue
        for lineno, line in enumerate(text.split("\n"), start=1):
            if LOOSE_RE.search(line) and not (RAW_RE.search(line) or PROMOTED_RE.search(line)):
                bad.append((rel, lineno, line.strip()))
    return bad


# ---------------------------------------------------------------------------
# Ticket store
# ---------------------------------------------------------------------------


def tickets_base(root: str) -> str:
    return os.path.join(root, TICKETS_DIR)


def ticket_dir(root: str, tid: int) -> tuple[Optional[str], bool]:
    """Return (dir, is_closed) for a ticket, or (None, False) if absent."""
    open_dir = os.path.join(tickets_base(root), str(tid))
    closed_dir = os.path.join(tickets_base(root), CLOSED_SUBDIR, str(tid))
    if os.path.isdir(open_dir):
        return open_dir, False
    if os.path.isdir(closed_dir):
        return closed_dir, True
    return None, False


def existing_ids(root: str) -> set[int]:
    ids: set[int] = set()
    base = tickets_base(root)
    for parent in (base, os.path.join(base, CLOSED_SUBDIR)):
        if os.path.isdir(parent):
            for name in os.listdir(parent):
                if name.isdigit() and os.path.isdir(os.path.join(parent, name)):
                    ids.add(int(name))
    return ids


def next_id(root: str) -> int:
    ids = existing_ids(root)
    return max(ids) + 1 if ids else 1


def load_tickets(root: str) -> dict[int, Ticket]:
    out: dict[int, Ticket] = {}
    base = tickets_base(root)
    for closed, parent in ((False, base), (True, os.path.join(base, CLOSED_SUBDIR))):
        if not os.path.isdir(parent):
            continue
        for name in sorted(os.listdir(parent)):
            tdir = os.path.join(parent, name)
            md = os.path.join(tdir, "ticket.md")
            if not (name.isdigit() and os.path.isfile(md)):
                continue
            fm = parse_frontmatter(read_text(md))
            tid = int(name)
            out[tid] = Ticket(
                id=tid,
                title=fm.get("title", ""),
                status=fm.get("status", "OPEN"),
                priority=fm.get("priority", "medium"),
                area=fm.get("area", ""),
                dir=tdir,
                closed=closed,
            )
    return out


def ticket_template(tid: int, title: str, priority: str, area: str, created: str) -> str:
    return (
        f"---\n"
        f"id: {tid}\n"
        f"title: {title}\n"
        f"status: OPEN\n"
        f"priority: {priority}\n"
        f"area: {area}\n"
        f"created: {created}\n"
        f"---\n\n"
        f"## Description\n\n"
        f"{title}\n\n"
        f"## Log\n\n"
        f"- {created} created (OPEN)\n\n"
        f"## Attachments\n\n"
        f"## Code references\n\n"
        f"{REFS_BEGIN}\n"
        f"{REFS_END}\n"
    )


def create_ticket(root: str, tid: int, title: str, priority: str, area: str) -> str:
    tdir = os.path.join(tickets_base(root), str(tid))
    os.makedirs(tdir, exist_ok=True)
    write_text(os.path.join(tdir, "ticket.md"), ticket_template(tid, title, priority, area, today()))
    return tdir


# ---------------------------------------------------------------------------
# ticket.md text surgery (frontmatter / sections / refs block)
# ---------------------------------------------------------------------------


def _join(lines: list[str]) -> str:
    text = "\n".join(lines)
    return text if text.endswith("\n") else text + "\n"


def parse_frontmatter(text: str) -> dict[str, str]:
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    fm: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" in line:
            key, value = line.split(":", 1)
            fm[key.strip()] = value.strip()
    return fm


def set_frontmatter_field(text: str, key: str, value: str) -> str:
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        fail("ticket.md has no frontmatter")
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        fail("ticket.md frontmatter is not terminated")
    for i in range(1, end):
        if ":" in lines[i] and lines[i].split(":", 1)[0].strip() == key:
            lines[i] = f"{key}: {value}"
            break
    else:
        lines.insert(end, f"{key}: {value}")
    return _join(lines)


def append_to_section(text: str, header: str, entry: str) -> str:
    """Insert `entry` at the end of the `## Header` section (before next `## `)."""
    lines = text.split("\n")
    try:
        start = next(i for i, l in enumerate(lines) if l.strip() == header)
    except StopIteration:
        # Section missing: append it at the end.
        return _join(lines + ["", header, "", entry])
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")), len(lines))
    while end - 1 > start and lines[end - 1].strip() == "":
        end -= 1
    lines.insert(end, entry)
    return _join(lines)


def replace_refs(text: str, ref_lines: list[str]) -> str:
    lines = text.split("\n")
    begin = next((i for i, l in enumerate(lines) if l.strip().startswith("<!-- refs:auto")), None)
    end = next((i for i, l in enumerate(lines) if l.strip() == REFS_END), None)
    if begin is None or end is None or end < begin:
        return _join(lines + ["", "## Code references", "", REFS_BEGIN, *ref_lines, REFS_END])
    return _join(lines[: begin + 1] + ref_lines + lines[end:])


# ---------------------------------------------------------------------------
# Status transitions (shared by `set` and `close`)
# ---------------------------------------------------------------------------


def reconcile_dir(root: str, tid: int, status: str) -> str:
    """Move a ticket between the open area and `closed/` to match its status."""
    cur, closed = ticket_dir(root, tid)
    if cur is None:
        fail(f"ticket #{tid} not found")
    want_closed = status == "CLOSED"
    if want_closed and not closed:
        dst = os.path.join(tickets_base(root), CLOSED_SUBDIR, str(tid))
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.move(cur, dst)
        return dst
    if not want_closed and closed:
        dst = os.path.join(tickets_base(root), str(tid))
        shutil.move(cur, dst)
        return dst
    return cur


def update_status(root: str, tid: int, new_status: str, comment: Optional[str]) -> None:
    tdir, _ = ticket_dir(root, tid)
    if tdir is None:
        fail(f"ticket #{tid} not found")
    md = os.path.join(tdir, "ticket.md")
    text = read_text(md)
    old = parse_frontmatter(text).get("status", "OPEN")
    text = set_frontmatter_field(text, "status", new_status)
    transition = f"{old} -> {new_status}" if old != new_status else new_status
    log = f"- {today()} {transition}" + (f": {comment}" if comment else "")
    text = append_to_section(text, "## Log", log)
    write_text(md, text)
    reconcile_dir(root, tid, new_status)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def cmd_promote(root: str, _args) -> int:
    raw = [m for m in scan_markers(root) if m.raw]
    if not raw:
        print("No raw TODOs to promote.")
        return 0
    nid = next_id(root)
    by_file: dict[str, list[Marker]] = {}
    for m in raw:
        by_file.setdefault(m.path, []).append(m)

    for rel in sorted(by_file):
        path = os.path.join(root, rel)
        lines = read_text(path).split("\n")
        for m in sorted(by_file[rel], key=lambda x: x.line):
            line = lines[m.line - 1]
            # Insert `#<id>` right after the leading `TODO` keyword.
            cut = m.col + len("TODO")
            lines[m.line - 1] = line[:cut] + f"#{nid}" + line[cut:]
            create_ticket(root, nid, m.msg, m.priority, m.area)
            print(f"  #{nid}  {rel}:{m.line}  {m.msg}")
            nid += 1
        write_text(path, "\n".join(lines))
    print(f"Promoted {len(raw)} TODO(s). Review the edits, then commit.")
    return 0


def cmd_new(root: str, args) -> int:
    if args.priority not in PRIORITIES:
        fail(f"priority must be one of {', '.join(PRIORITIES)}")
    tid = next_id(root)
    create_ticket(root, tid, args.message, args.priority, args.area or "")
    print(f"Created ticket #{tid} (no code anchor). Edit {TICKETS_DIR}/{tid}/ticket.md")
    return 0


def cmd_set(root: str, args) -> int:
    status = args.status.upper()
    if status not in STATUSES:
        fail(f"status must be one of {', '.join(STATUSES)}")
    update_status(root, args.id, status, args.comment)
    print(f"#{args.id} -> {status}")
    return 0


def cmd_note(root: str, args) -> int:
    tdir, _ = ticket_dir(root, args.id)
    if tdir is None:
        fail(f"ticket #{args.id} not found")
    md = os.path.join(tdir, "ticket.md")
    write_text(md, append_to_section(read_text(md), "## Log", f"- {today()} note: {args.comment}"))
    print(f"#{args.id} note added")
    return 0


def cmd_attach(root: str, args) -> int:
    tdir, _ = ticket_dir(root, args.id)
    if tdir is None:
        fail(f"ticket #{args.id} not found")
    src = args.file
    if not os.path.isfile(src):
        fail(f"no such file: {src}")
    size = os.path.getsize(src)
    if not args.binary:
        with open(src, "rb") as fh:
            looks_binary = b"\0" in fh.read(8192)
        if looks_binary:
            fail(f"{src} looks binary; pass --binary to attach it anyway")
        if size > ATTACH_SIZE_WARN:
            fail(f"{src} is {size // 1024} KiB (> {ATTACH_SIZE_WARN // 1024} KiB); pass --binary to confirm")
    name = os.path.basename(src)
    shutil.copy2(src, os.path.join(tdir, name))
    md = os.path.join(tdir, "ticket.md")
    write_text(md, append_to_section(read_text(md), "## Attachments", f"- {name}"))
    print(f"#{args.id} attached {name}")
    return 0


def cmd_show(root: str, args) -> int:
    tdir, closed = ticket_dir(root, args.id)
    if tdir is None:
        fail(f"ticket #{args.id} not found")
    print(read_text(os.path.join(tdir, "ticket.md")).rstrip())
    locs = [f"{m.path}:{m.line}" for m in scan_markers(root) if m.id == args.id]
    print("\nLive code references:" + (" (none)" if not locs else ""))
    for loc in locs:
        print(f"  {loc}")
    if closed:
        print("\n(closed)")
    return 0


def cmd_list(root: str, args) -> int:
    tickets = load_tickets(root)
    locs: dict[int, int] = {}
    for m in scan_markers(root):
        if m.id is not None:
            locs[m.id] = locs.get(m.id, 0) + 1

    rows = list(tickets.values())
    if args.status:
        rows = [t for t in rows if t.status == args.status.upper()]
    if args.area:
        rows = [t for t in rows if t.area == args.area]
    if args.priority:
        rows = [t for t in rows if t.priority == args.priority]
    if not rows:
        print("No tickets.")
        return 0

    rows.sort(key=lambda t: (STATUSES.index(t.status), PRIORITY_RANK.get(t.priority, 9), t.id))
    cur_status = None
    for t in rows:
        if t.status != cur_status:
            cur_status = t.status
            print(f"\n{cur_status}")
        area = f" [{t.area}]" if t.area else ""
        refs = locs.get(t.id, 0)
        print(f"  #{t.id:<3} {t.priority:<6}{area} {t.title}  ({refs} ref)")
    return 0


def _regen_refs(root: str) -> list[str]:
    """Regenerate every ticket's refs:auto block. Returns changed ticket.md paths."""
    locs: dict[int, list[str]] = {}
    for m in scan_markers(root):
        if m.id is not None:
            locs.setdefault(m.id, []).append(f"- {m.path}:{m.line}")
    changed = []
    for tid, t in load_tickets(root).items():
        md = os.path.join(t.dir, "ticket.md")
        text = read_text(md)
        updated = replace_refs(text, sorted(locs.get(tid, [])))
        if updated != text:
            write_text(md, updated)
            changed.append(md)
    return changed


def cmd_sync(root: str, args) -> int:
    changed = _regen_refs(root)
    for md in changed:
        print(f"synced {os.path.relpath(md, root)}")
        if args.stage:
            git_add(root, md)
    if not changed:
        print("Code references already up to date.")
    return 0


def cmd_close(root: str, args) -> int:
    tdir, closed = ticket_dir(root, args.id)
    if tdir is None:
        fail(f"ticket #{args.id} not found")
    if closed:
        fail(f"ticket #{args.id} is already closed")

    markers = [m for m in scan_markers(root) if m.id == args.id]
    by_file: dict[str, list[Marker]] = {}
    for m in markers:
        by_file.setdefault(m.path, []).append(m)

    print(f"Closing #{args.id} — removing {len(markers)} marker(s):")
    for m in markers:
        print(f"  {m.path}:{m.line}  {m.msg}")
    if args.dry_run:
        print("(dry run — nothing changed)")
        return 0

    for rel, ms in by_file.items():
        path = os.path.join(root, rel)
        token = lang_token(rel)
        lines = read_text(path).split("\n")
        drop: set[int] = set()
        for m in ms:
            idx = m.line - 1
            new = _strip_marker(lines[idx], token, m.col)
            if new is None:
                drop.add(idx)
            else:
                lines[idx] = new
        kept = [l for i, l in enumerate(lines) if i not in drop]
        write_text(path, "\n".join(kept))

    update_status(root, args.id, "CLOSED", args.comment)
    print(f"#{args.id} closed and archived to {TICKETS_DIR}/{CLOSED_SUBDIR}/{args.id}/")
    return 0


def _strip_marker(line: str, token: str, todo_col: int) -> Optional[str]:
    """Return the line with the trailing comment removed, or None to drop the line."""
    open_idx = line.find(token)
    if open_idx == -1 or open_idx > todo_col:
        open_idx = todo_col
    before = line[:open_idx]
    return None if before.strip() == "" else before.rstrip()


def cmd_check(root: str, _args) -> int:
    markers = scan_markers(root)
    tickets = load_tickets(root)
    errors: list[str] = []
    warnings: list[str] = []

    anchored_ids: set[int] = set()
    for m in markers:
        if m.id is None:
            continue
        anchored_ids.add(m.id)
        t = tickets.get(m.id)
        if t is None:
            errors.append(f"{m.path}:{m.line}: TODO#{m.id} has no ticket directory")
        elif t.closed:
            errors.append(f"{m.path}:{m.line}: TODO#{m.id} references a CLOSED ticket")

    for tid, t in tickets.items():
        if t.status in OPEN_STATUSES and tid not in anchored_ids:
            warnings.append(f"#{tid} is {t.status} but has no code marker")

    for rel, lineno, snippet in find_malformed(root):
        errors.append(f"{rel}:{lineno}: malformed TODO: {snippet}")

    for w in warnings:
        print(f"warning: {w}")
    for e in errors:
        print(f"error: {e}", file=sys.stderr)
    if errors:
        print(f"\n{len(errors)} error(s), {len(warnings)} warning(s)", file=sys.stderr)
        return 1
    print(f"OK ({len(tickets)} ticket(s), {len(warnings)} warning(s))")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="ticket", description="Code-comment-backed ticket tracker.")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("promote", help="turn raw TODOs into numbered tickets")

    sp = sub.add_parser("new", help="create a ticket without a code anchor")
    sp.add_argument("message")
    sp.add_argument("--priority", default="medium")
    sp.add_argument("--area", default="")

    sp = sub.add_parser("set", help="change status and append a log entry")
    sp.add_argument("id", type=int)
    sp.add_argument("status")
    sp.add_argument("comment", nargs="?")

    sp = sub.add_parser("note", help="append a log entry without changing status")
    sp.add_argument("id", type=int)
    sp.add_argument("comment")

    sp = sub.add_parser("attach", help="copy a file into the ticket directory")
    sp.add_argument("id", type=int)
    sp.add_argument("file")
    sp.add_argument("--binary", action="store_true", help="allow binary/large files")

    sp = sub.add_parser("show", help="render a ticket and its live code references")
    sp.add_argument("id", type=int)

    sp = sub.add_parser("list", help="list tickets")
    sp.add_argument("--status")
    sp.add_argument("--area")
    sp.add_argument("--priority")

    sp = sub.add_parser("sync", help="regenerate the refs:auto block in every ticket")
    sp.add_argument("--stage", action="store_true", help="git add changed ticket.md files")

    sp = sub.add_parser("close", help="remove the code marker(s) and archive the ticket")
    sp.add_argument("id", type=int)
    sp.add_argument("comment", nargs="?")
    sp.add_argument("--dry-run", action="store_true", help="preview removals only")

    sub.add_parser("check", help="integrity check (used by the pre-commit hook)")
    return p


COMMANDS = {
    "promote": cmd_promote,
    "new": cmd_new,
    "set": cmd_set,
    "note": cmd_note,
    "attach": cmd_attach,
    "show": cmd_show,
    "list": cmd_list,
    "sync": cmd_sync,
    "close": cmd_close,
    "check": cmd_check,
}


def main(argv: list[str]) -> int:
    args = build_parser().parse_args(argv)
    return COMMANDS[args.cmd](repo_root(), args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
